### ISSUE TITLE
Binary distribution security

### ISSUE THREAD

**Issue by Zero3** [nickbnf/glogg#146]
It would be appreciated if there was more security around the distribution of the glogg binaries. For example, the Windows executable linked from the website is unsigned and is served over HTTP. I would love to use glogg on production servers, but executing binaries distributed in this way makes me somewhat uneasy.

I suggest the following 2 improvements:

1) Only serve the website and binaries over HTTPS. This should be easy and free with https://letsencrypt.org/.

2) Sign the Windows executables with a code certificate. This is probably more complicated and a suitable certificate likely costs some amount of money.

**Comment by nickbnf** [comment]
I will consider switching to https on the website but probably won't bother getting a certificate on Windows as I don't use the platform. The MD5 for the installer is distributed in the release email, it's not foolproof, but considerably reduce the risk as the email is archived in Google Groups. I'll also sign the email from now on.

**Comment by Zero3** [comment]
@nickbnf Alright. Looking forward for the HTTPS upgrade.

You should be aware that MD5 is *not* a safe hashing algorithm for this purpose anymore. On the contrary, it will give a false sense of security, since it is now trivial to produce another binary with the same hash. Please see https://en.wikipedia.org/wiki/MD5#Security for more info.

**Comment by jdnixx** [comment]
Hey not sure if it's just me, I think I have a malware infection doing something to my DNS so couldn't say for sure (which is why I'm concerned about it in the first place) but this doesn't seem to be resolved yet:
![image](https://user-images.githubusercontent.com/24235975/86519017-965c4f00-be04-11ea-82ef-ef6fe25a0538.png)

Also echoing @Zero3 's comment about MD5, should ditch that.
